### ISSUE TITLE
Tooltip inside a <p></p> results in a warning

### ISSUE THREAD

**Issue by dropfen** [wwayne/react-tooltip#210] opened 2016-10-19 12:38 UTC
It actually works, but the default tooltip wrapper is a `<div>`
And this makes it problematic to use it within a `<p>` tag.. In our case we need a tooltip for an img which is inner p tag.. we use span based template to show the tooltip content, but we get a warning message because the tooltip wrapper is a div.

`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See ReactMarkdown > p > ... > Image > ItemIconWithTooltip > ReactTooltip > div.`

**Comment by wwayne** [comment] 2017-02-07 03:51
Thanks, merged the PR, will release in 3.2.4

**Closed by wwayne** 2017-02-07 03:51 UTC

**Comment by joaoreynolds** [comment] 2019-01-31 00:13
For future readers - to save the few minutes it took me to go read the docs. You can pass in the option `wrapper="span"` (default remains `div`) which will get around this error.

**Comment by Aryaman73** [comment] 2021-08-02 22:24
Not sure if this is working as intended, but it looks like with `wrapper="span"` there is a p tag there, and I'm getting a similar error: 

![image](https://user-images.githubusercontent.com/53343807/127930973-cd322b00-0b34-424e-ad9f-0e879de539ca.png)

I'm using `v4.2.21`

**Comment by MilanLund** [comment] 2023-01-31 21:14
I am experiencing this issue too `v5.7.1`. 
Using with Next.js App Directory inside a client component.
