### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by suhaotian** [wwayne/react-tooltip#126] opened 2016-06-29 15:54 UTC
![image](https://cloud.githubusercontent.com/assets/6512574/16459242/b9a9d092-3e54-11e6-83b7-33371291eeb8.png)

latest chrome, react-tooltip@3.0.7

**Comment by wwayne** [comment] 2016-07-01 09:38
Should be fixed in 3.0.8

**Comment by cheton** [comment] 2016-07-01 10:38
I've updated react-tooltip to v3.0.8, but Google Chrome still reported this error when dragging around some sortable widgets that contains the ReactTooltip component.

![image](https://cloud.githubusercontent.com/assets/447801/16519273/4e1ec014-3fba-11e6-934c-c690e89622b5.png)

Source code:
https://github.com/cheton/cnc/blob/master/src/web/components/widgets/axes/Toolbar.jsx#L48

**Comment by wwayne** [comment] 2016-07-01 10:57
@cheton I did more tests, but looks I can't reproduce the bug, is it possible because of the cache?

**Comment by cheton** [comment] 2016-07-01 11:45
I made a simple example on webpackbin but cannot reproduce this case with this example. Maybe it only happened in a complex scenario.

Example: http://www.webpackbin.com/E1Te-SJIZ

**Comment by wwayne** [comment] 2016-07-01 13:22
Previously, the bug is caused when re-calculating the position of the tooltip, for example, when the tooltip in the corner and will be out of the screen, and re-calculating will get the tooltip back to the inner. I don't know if your case relate to this kind of things.

**Comment by cheton** [comment] 2016-07-01 14:30
When I tried to drag a sortable widget (w/ ReactTooltip component), Chrome browser will soon close the Developer Tool and terminate my browser session, it makes me hard to track what's going wrong. I may turn to use a workaround by disabling ReactTooltip component when the `dragenter` event is fired.

**Comment by cheton** [comment] 2016-07-02 00:19
Now I'm using react-bootstrap tooltip and it works for me. Thank you, anyway.
https://react-bootstrap.github.io/components.html#tooltips

**Comment by wwayne** [comment] 2016-07-02 00:22
Hmm, okay, just thinking how to reproduce : )
Closing the ticket, will open if someone has the same problem and find the reason

**Closed by wwayne** 2016-07-02 00:22 UTC
