### ISSUE TITLE
All tooltips are visible instead of current

### ISSUE THREAD

**Issue by VanDavv** [wwayne/react-tooltip#283] opened 2017-04-06 13:40 UTC
Copied from https://github.com/wwayne/react-tooltip/issues/89 since it still occurs:

When several tooltips are instantiated on a single page, the data-event click doesn't act fully as a toggle to hide all active tooltips. Not sure if this is the desired behavior but it would make sense that only the current tooltip be activated at a time.

**Comment by monrus** [comment] 2017-06-20 11:56
what with this issue?

**Comment by apandichi** [comment] 2017-11-02 12:41
Hey @wwayne, any chance we can get this fixed?
I created a simple React project that demonstrates this issue: 
https://github.com/apandichi/demo-tooltip-hide-issue

Steps to reproduce the problem: 
1. Click the first face.
2. Click the second face.
I expect that the first tooltip is hidden (as per globalEventOff='click'). Instead, both tooltips are displayed.

**Comment by mikebabb** [comment] 2018-08-20 15:34
Is there a fix planned for this issue? I'm guessing not given its age. It can apparently be resolved by only having one tooltip component on a given page, but it'd be great to not have to refactor the way tooltips have been implemented across our application just to work around this. `eventPropagationMode` and `globalEventOff` don't solve it :disappointed:

**Comment by apandichi** [comment] 2018-08-20 16:42
Pinging @aronhelser as he seems to be more active lately

**Comment by aronhelser** [comment] 2018-08-20 17:35
I won't be able to solve it, but a PR would be welcome. Seems like looking at what happens inside the globalEventOff handler is a place to start...

**Comment by apandichi** [comment] 2018-09-19 11:27
@aronhelser Please see the referenced PR and the my updated demo app. This seems to have solved the issue. 

Please review, I'm not sure if I dealt with this correctly. I used the `isCapture` from `props` instead of the `isCapture()` decorator. I couldn't figure out what the `target` is supposed to be in that global scope where `globalEventOff` is handled.

Thanks!

**Closed** 2018-09-20 23:54 UTC
