### ISSUE TITLE
Tooltip jitters on mousemove when effect is "solid"

### ISSUE THREAD

**Issue by mattzeunert** [wwayne/react-tooltip#138] opened 2016-07-16 18:00 UTC
On mousemove it seems like the right edge of the div is moving by 1px.

![react-tooltip-jitter](https://cloud.githubusercontent.com/assets/1303660/16896295/5b9a2a8e-4b87-11e6-9bfb-c1924a96ef16.gif)

**Comment by wwayne** [comment] 2016-07-17 00:27
Same with https://github.com/wwayne/react-tooltip/issues/51

**Comment by wwayne** [comment] 2016-07-18 04:20
I've tested it with two different macbook, one is non-retina, the other is retina, but I can't reproduce this....

**Comment by mir3z** [comment] 2016-07-19 12:23
I can reproduce this on Ubuntu 14.04 with nouveau driver, Chrome Version 49.0.2623.87 (64-bit)

**Comment by johnny353535** [comment] 2016-07-20 09:15
I can reproduce it in Chrome 51, external non-retina monitor. I'm on OSX Yosemite on a Macbook Pro.

**Comment by wwayne** [comment] 2016-07-27 09:02
Should be fixed in `3.1.0`

**Closed by wwayne** 2016-07-27 09:02 UTC
Labels: Question
