### ISSUE TITLE
`Clickable` option on the demo doesn't work

### ISSUE THREAD

**Issue by chulanovskyi** [wwayne/react-tooltip#499] opened 2019-06-25 13:20 UTC
At the very bottom of the [demo site](https://react-tooltip.netlify.com/) there is a section with a `clickable` prop example, but - the problem is described in the title. When I try to type something into the input - it doesn't react on any event, clicking, typing...

![image](https://user-images.githubusercontent.com/13966263/60101580-aeff4700-9764-11e9-898d-e18542a14c48.png)

OS: 18.04.2 LTS
Tested browsers:
- Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- Firefox 67.0.4 (64-bit)

**Comment by aronhelser** [comment] 2019-06-25 19:10
This should be a matter of setting the `pointer-events` style correctly - I
thought this worked when the example was added. Can you take a look?

**Comment by chulanovskyi** [comment] 2019-06-25 19:26
Tested on mobile (chrome) - still not working. Will check later from the desktop...

**Comment by tihuan** [comment] 2019-07-16 23:42
It looks like the [example site](https://react-tooltip.netlify.com)'s `index.js` response doesn't have `.__react_component_tooltip.allow_click` css rule. Possibly because `standalone/react-tooltip.js` doesn't have that rule?

E.g., 

https://github.com/wwayne/react-tooltip/blob/master/standalone/react-tooltip.js

For `allow_hover`, there's `__react_component_tooltip.allow_hover{pointer-events:auto}`, so I for `allow_click`, was expecting to see `__react_component_tooltip.allow_click{pointer-events:auto}` there as well?

Could this be the root cause?

Thanks!

@aronhelser

**Comment by mawburn** [comment] 2019-09-25 19:44
Any updates on this? It seems like it extends into the library itself and setting the `clickable` option doesn't do anything.

**Comment by Rogger794** [comment] 2020-02-06 02:30
Hi @chulanovskyi, already fixed in the new release, let me know if it works for you.

**Closed** 2020-02-06 02:39 UTC
