### ISSUE TITLE
Don't work after build and deploy

### ISSUE THREAD

**Issue by StanBorovko** [wwayne/react-tooltip#565] opened 2020-03-18 11:50 UTC
Hello! I'm using react-tooltip in my project and at local server it works great in development and production builds. In devtools I can see all element's attributes changes after mouse over the element with tooltip. But when I deploy my app to AWS server, tooltips refuse to show and element's attributes don't change anymore. How I can fix this problem? 

Works correct:
<img width="882" alt="Снимок экрана 2020-03-18 в 13 47 16" src="https://user-images.githubusercontent.com/34895740/76957791-22fb0400-691f-11ea-8d34-82bff1051fb7.png">

Works wrong:
<img width="882" alt="Снимок экрана 2020-03-18 в 13 47 44" src="https://user-images.githubusercontent.com/34895740/76957819-2b533f00-691f-11ea-93d1-4d04d4b53158.png">

**Comment by Jarch09** [comment] 2020-03-31 05:55
@StanBorovko - how are you deploying on AWS? 

If you are building a production-style bundle on your local machine, and it's running correctly, that leads me to suspect that the issue is not with react-tooltip... ;-)

**Comment by Jarch09** [comment] 2020-04-08 17:25
Think we can close this issue

**Closed** 2020-04-08 18:19 UTC
